server:
  port: 7411
spring:
  application:
    name: eureka-consumer-analyze
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/,http://peer3:7103/eureka/
feign:
  hystrix:
    enabled: true
