server:
  port: 7202
spring:
  application:
    name: eureka-provider-analyze
  datasource:
      url: jdbc:mysql://192.168.43.204:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/
mybatis:
 mapper-locations: classpath*:mapper/*.xml
 type-aliases-package: com.zking.lxs.spring.model